### ISSUE TITLE
License for weights

### ISSUE THREAD

**Issue by ieee8023** [xinario/chestViewSplit#2]
I'd like to add this model to the TorchXRayVision library (https://github.com/mlmed/torchxrayvision). 

Can you tell me the license for the weights file? The library uses an Apache license.

**Comment by xinario** [comment]
Glad you find it useful. I just put a Apache license to the repo. This might be the easiest for you to proceed.

**Comment by ieee8023** [comment]
I added it to the library! Here is a demo: https://github.com/mlmed/torchxrayvision/blob/master/scripts/view_classifier.ipynb
